#%RAML 1.0 DataType
properties:
  ref_phmcy_prvdr_tid: number
  start_dt: datetime
  end_dt": datetime
  ncpdp_id: datetime
  npi_id: number
  dea_nbr_id": string
  fed_tax_id: number
  state_lcns_id: number
  name: string
  dba_name: string
  store_nbr_txt: integer
  strt_addr_1: string
  strt_addr_2: string
  city: string
  srch_city: string
  st_cd: integer
  zip_code": number
  phn_txt: number
  fax_txt : number
  email_txt: string
  loc_descr: string
  loc_cnty_fips: number
  loc_msa: number
  loc_pmsa: number
  opn_24_hrs_bln: string
  hrs_descr: string
  acpt_e_rx_bln: string
  dlvry_svc_bln: string
  dme_bln: string
  cngrsnl_dstrct_txt: string
  lang_1_cd: string
  lang_2_cd: string
  mail_strt_addr_1: string
  mail_strt_addr_2: string
  mail_city: string
  mail_srch_city: string
  mail_st_cd: number
  mail_zip_code: number
  cntct_first_name: string
  cntct_last_name: string
  cntct_middle_name: string
  cntct_title: string
  cntct_phn_txt: string
  cntct_email_txt: string
  dspnsr_cls_cd: number
  pri_dspnsr_typ_cd: number
  sec_dspnsr_typ_cd: number
  ver_nbr: number
  create_dt: datetime
  create_user: string
  create_sys_cd: number
  last_updt_dt: datetime
  last_updt_user: string
  last_updt_sys_cd: number
  dea_expir_date: datetime
  reinstmt_date: datetime
  state: string


           