#%RAML 1.0 DataType

properties:
    in_source_group_id:
      type: string
      required: true
    in_initiative_id:
      type: string
      required: true
    in_last_updated_by:
      type: string
      required: true