#%RAML 1.0 DataType
properties:
  name:
   type: string
   required: true
  state: 
   type: string
   required: true
  zipCode: 
   type: number
   required: true
  ncpdp: 
   type: number
   required: true
  npi: 
   type: number
   required: true
  phone: 
   type: number
   required: true

