#%RAML 1.0 NamedExample
{
  "insertEmsMessageRequest": {
    "systemCode": "string",
    "programId": "string",
    "messageTypeCode": "string",
    "messagePkId": "string",
    "userId": "string",
    "message": "string"
  }
}