#%RAML 1.0 NamedExample
{
  "NDPRxTransferGroupAndNumber": {
    "in_img_str": "string",
    "in_doc_str": "string",
    "in_rcvd_pic": "string",
    "in_rcvd_pharmacy_name": "string",
    "in_rcvd_pharmacy": "string",
    "in_rcvd_fax_nbr": "string",
    "in_batch_number": "number",
    "in_transactionid": "number"
  }
}