#%RAML 1.0 NamedExample
{
    "PRSSearchPrescriber": {
        "identifierType": "string",
        "identifier": "string",
        "firstName": "string",
        "lastName": "string",
        "addressLine1": "string",
        "city": "string",
        "state": "string",
        "zipCode": "string",
        "phone": "string",
        "prescriberId": "string"
    }
}