#%RAML 1.0 NamedExample
{
  "PRSSearchPrescriberResponse": {
    "prescriber": [
      {
        "id": "2311",
        "firstName": "sisco",
        "middleName": "lsd",
        "lastName": "string",
        "suffix": "string",
        "retired": "false",
        "validationStatus": "string",
        "amaOptOut": "Y",
        "amaStartDate": "2016-11-07",
        "addressList": [
          {
            "id": "string",
            "addressLine1": "string",
            "addressLine2": "string",
            "city": "string",
            "state": "string",
            "zipCode": "string",
            "addressType": "string",
            "validationStatus": "string"
          },
          {
            "id": "string",
            "addressLine1": "string",
            "addressLine2": "string",
            "city": "string",
            "state": "string",
            "zipCode": "string",
            "addressType": "string",
            "validationStatus": "string"
          }
        ],
        "commList": [
          {
            "id": "string",
            "commType": "string",
            "commValue": "string",
            "validationStatus": "string"
          },
          {
            "id": "string",
            "commType": "string",
            "commValue": "string",
            "validationStatus": "string"
          }
        ],
        "identifierList": [
          {
            "id": "string",
            "identifierType": "string",
            "identifierValue": "string",
            "state": "string",
            "expirationDate": "2016-08-29",
            "classQualifier": "string",
            "pdmaEligibility": "string",
            "validationStatus": "string"
          },
          {
            "id": "string",
            "identifierType": "string",
            "identifierValue": "string",
            "state": "string",
            "expirationDate": "2016-08-29",
            "classQualifier": "string",
            "pdmaEligibility": "string",
            "validationStatus": "string"
          }
        ]
      }
    ]
  }
}
